#FROM rnakato/ubuntu_gpu:pytorch-1.5-cuda10.1-cudnn7-devel
#FROM rnakato/ubuntu_gpu:pytorch-1.10.0-cuda11.3-cudnn8-devel
FROM rnakato/ubuntu_gpu:nvidia-11.5.1-cudnn8-devel-ubuntu20.04
LABEL maintainer "Ryuichiro Nakato <rnakato@iqb.u-tokyo.ac.jp>"

USER root
WORKDIR /work
ENV PATH ${PATH}:/work

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    apt-file \
    apt-utils \
    build-essential \
    bzip2 \
    ca-certificates \
    cmake \
    curl \
    emacs \
    eog \
    evince \
    gawk \
    gdebi-core \
    gedit \
    gfortran \
    git \
    gnupg \
    htop \
    imagemagick \
    libatlas-base-dev \
    libblas-dev \
    libboost-all-dev \
    libbz2-dev \
    libcurl4-gnutls-dev \
    libfreetype6-dev \
    libgdal-dev \
    libgit2-dev \
    libglu1-mesa-dev \
    libgsl-dev \
    libhdf5-dev \
    libhdf5-serial-dev \
    liblapack3 \
    liblapack-dev \
    libssl-dev \
    libudunits2-dev \
    libv8-dev \
    libx11-dev \
    make \
    openjdk-8-jdk-headless \
    openjdk-8-jre \
    pigz \
    psmisc \
    qtbase5-dev qttools5-dev-tools qt5-default \
    samtools \
    sudo \
    unzip \
    vim \
    xorg \
    zlib1g-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
#   libcurl4-openssl-dev

# R 4.0
RUN echo "deb https://cran.rstudio.com/bin/linux/ubuntu bionic-cran40/" | tee -a /etc/apt/sources.list \
    && curl -sL "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x51716619E084DAB9" | apt-key add \
    && apt update \
    && apt install -y r-base r-base-core r-recommended r-base-dev libclang-dev libxkbcommon-x11-0 \
    && apt upgrade -y \
    && apt autoremove -y \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/lib/x86_64-linux-gnu/libhdf5_serial.so.100 /usr/lib/x86_64-linux-gnu/libhdf5.so.100 \
    && ln -s /usr/lib/x86_64-linux-gnu/libhdf5_serial_hl.so.100 /usr/lib/x86_64-linux-gnu/libhdf5_hl.so.100

# R packages
RUN R -e "install.packages(c('BiocManager'))"
#    R -e "BiocManager::install(version = '3.12', ask = FALSE)"
RUN R CMD javareconf
RUN R -e "install.packages(c('repr', 'IRdisplay', 'evaluate', 'crayon', 'pbdZMQ', 'devtools', 'uuid', 'digest','Rcpp' ,'devtools','sf','tidyverse','xlsx','hdf5r','igraph','usethis'))" \
    && R -e "BiocManager::install(c('multtest','rhdf5'))"

# Rstudio
RUN curl -LO https://download1.rstudio.org/desktop/bionic/amd64/rstudio-1.4.1106-amd64.deb \
    && gdebi -n rstudio-1.4.1106-amd64.deb \
    && rm rstudio-1.4.1106-amd64.deb

#RUN R -e "install.packages(c('keras', 'tensorflow'), repos='https://cran.ism.ac.jp/')"
#RUN R -e "reticulate::py_config()"
#RUN echo "Sys.setenv(RETICULATE_PYTHON = '/opt/conda/bin/python3')" > $HOME/.Rprofile
#RUN R -e "tensorflow::install_tensorflow()"

# Python
RUN conda update -y conda \
    && pip install -U pip \
    && conda config --add channels conda-forge
RUN conda install numpy numpy_groupies scipy matplotlib pandas seaborn scikit-learn notebook dash plotly black bokeh h5py click jupyter jupyterlab pytables \
    && pip install -U jupyterthemes jupyter_contrib_nbextensions python-igraph umap-learn numba Cython

ADD conf conf

RUN useradd -s /bin/bash -m rstudio \
    && echo "rstudio:rstudio" | chpasswd

RUN jupyter notebook --generate-config \
    && cat ./conf >> /root/.jupyter/jupyter_notebook_config.py \
    && rm ./conf
RUN R -e "devtools::install_github('IRkernel/IRkernel')" \
    && R -e "IRkernel::installspec(user = FALSE)"

#ENV XDG_RUNTIME_DIR /opt/

COPY jupyternotebook.sh jupyternotebook.sh
COPY rserver.sh rserver.sh
