FROM rnakato/ubuntu:2023.03
LABEL maintainer "Ryuichiro Nakato <rnakato@iqb.u-tokyo.ac.jp>"

USER root

WORKDIR /opt
ENV PATH /opt/conda/bin/:$PATH:/opt

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    apt-file \
    apt-utils \
    build-essential \
    bzip2 \
    ca-certificates \
    cmake \
    curl \
    default-jre \
    eog \
    evince \
    gawk \
    gdebi-core \
    gfortran \
    git \
    gnupg \
    htop \
    imagemagick \
    libatlas-base-dev \
    libblas-dev \
    libboost-all-dev \
    libbz2-dev \
    libcairo2-dev \
    libcurl4-gnutls-dev \
    libfreetype6-dev \
    libgdal-dev \
    libgit2-dev \
    libglu1-mesa-dev \
    libgsl-dev \
    libharfbuzz-dev \
    libfribidi-dev \
    libhdf5-dev \
    libhdf5-serial-dev \
    liblapack3 \
    liblapack-dev \
    libmagick++-dev \
    libssl-dev \
    libtool \
    libudunits2-dev \
    libv8-dev \
    libx11-dev \
    make \
    openjdk-8-jdk-headless \
    openjdk-8-jre \
    pigz \
    psmisc \
    qtbase5-dev qt5-qmake qtbase5-dev-tools qtchooser \
    sudo \
    unzip \
    vim \
    xorg \
    zlib1g-dev \
    && echo "deb https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/" | tee -a /etc/apt/sources.list \
    && curl -sL "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x51716619E084DAB9" | apt-key add \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
    r-base r-base-core r-recommended r-base-dev libclang-dev libxkbcommon-x11-0 \
    && apt-get upgrade -y \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

#RUN ln -s /usr/lib/x86_64-linux-gnu/libhdf5_serial.so.103 /usr/lib/x86_64-linux-gnu/libhdf5.so.103 \
#    && ln -s /usr/lib/x86_64-linux-gnu/libhdf5_serial_hl.so.103 /usr/lib/x86_64-linux-gnu/libhdf5_hl.so.103

# R packages
COPY .Rprofile /root/
RUN R -e "install.packages(c('BiocManager'))" \
    && R -e "BiocManager::install(ask = FALSE)" \
    && R CMD javareconf
RUN R -e "install.packages(c('repr', 'IRdisplay', 'evaluate', 'crayon', 'pbdZMQ', 'devtools', 'uuid', 'digest','Rcpp' ,'sf', 'tidyverse', 'xlsx', 'hdf5r', 'igraph', 'VennDiagram', 'usethis', 'graph'))"
RUN R -e "BiocManager::install(c('multtest','rhdf5'))" \
    && R -e "devtools::install_github('IRkernel/IRkernel')"

# Install Rstudio and create user
#RUN curl -LO https://download1.rstudio.org/desktop/bionic/amd64/rstudio-1.4.1106-amd64.deb \
RUN curl -LO https://download1.rstudio.org/electron/bionic/amd64/rstudio-2023.03.0-386-amd64.deb \
    && gdebi -n rstudio-2023.03.0-386-amd64.deb \
    && rm rstudio-2023.03.0-386-amd64.deb \
    && useradd -s /bin/bash -m rstudio \
    && echo "rstudio:rstudio" | chpasswd

# Python
RUN wget --quiet https://repo.anaconda.com/archive/Anaconda3-2023.03-Linux-x86_64.sh -O ~/anaconda.sh \
     && bash ~/anaconda.sh -b -p /opt/conda \
     && rm ~/anaconda.sh \
     && ln -s -f /opt/conda/bin/python /usr/bin/python
#     && ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh

RUN conda install numpy scipy matplotlib pandas seaborn scikit-learn scikit-learn-intelex \
    notebook dash plotly black bokeh h5py click jupyter jupyterlab pytables setuptools \
    sphinx sphinx_rtd_theme fastcluster numba Cython \
    && conda install -c conda-forge sphinx-autobuild nbsphinx python-igraph jupyterthemes jupyter_contrib_nbextensions umap-learn ncurses \
    && pip install --no-cache-dir sphinxcontrib.exceltable session_info tqdm

# MACS2-2.2.6
RUN wget https://mirrors.huaweicloud.com/repository/pypi/packages/21/0f/972b44c84d85e37d816beae88aa5ddad606bd757630d77dc2f558900a6ce/MACS2-2.2.6.tar.gz \
    && tar zxvf MACS2-2.2.6.tar.gz \
    && cd MACS2-2.2.6 \
    && python setup.py install \
    && rm -rf /opt/MACS2-2.2.6 /opt/MACS2-2.2.6.tar.gz

# Jupyter config
COPY conf conf
RUN jupyter notebook --generate-config \
    && cat ./conf >> ~/.jupyter/jupyter_notebook_config.py \
    && rm ./conf
RUN R -e "IRkernel::installspec(user = FALSE)"

COPY jupyternotebook.sh jupyternotebook.sh
COPY rserver.sh rserver.sh
COPY rstudio.sh rstudio.sh
RUN chmod +x /opt/*sh

USER ubuntu
CMD ["/bin/bash"]
