FROM rnakato/ubuntu:18.04
LABEL maintainer "Ryuichiro Nakato <rnakato@iqb.u-tokyo.ac.jp>"

USER root
WORKDIR /opt

ENV PATH /opt/conda/bin:${PATH}:/opt

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    apt-file \
    apt-utils \
    build-essential \
    bzip2 \
    ca-certificates \
    cmake \
    curl \
    emacs \
    eog \
    evince \
    gawk \
    gdebi-core \
    gedit \
    gfortran \
    git \
    gnupg \
    htop \
    imagemagick \
    libatlas-base-dev \
    libblas-dev \
    libboost-all-dev \
    libbz2-dev \
    libcurl4-openssl-dev \
    libfreetype6-dev \
    libgdal-dev \
    libglu1-mesa-dev \
    libgsl-dev \
    libhdf5-dev \
    libhdf5-serial-dev \
    liblapack3 \
    liblapack-dev \
    libssl-dev \
    libudunits2-dev \
    libx11-dev \
    make \
    openjdk-8-jdk-headless \
    openjdk-8-jre \
    pigz \
    psmisc \
    sudo \
    unzip \
    vim \
    xorg \
    zlib1g-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# R 4.0
RUN echo "deb https://cran.rstudio.com/bin/linux/ubuntu bionic-cran40/" | tee -a /etc/apt/sources.list \
    && curl -sL "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x51716619E084DAB9" | apt-key add \
    && apt update \
    && apt install -y r-base r-base-core r-recommended r-base-dev libclang-dev libxkbcommon-x11-0 \
    && apt upgrade -y \
    && apt autoremove -y \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/lib/x86_64-linux-gnu/libhdf5_serial.so.100 /usr/lib/x86_64-linux-gnu/libhdf5.so.100 \
    && ln -s /usr/lib/x86_64-linux-gnu/libhdf5_serial_hl.so.100 /usr/lib/x86_64-linux-gnu/libhdf5_hl.so.100

# R packages
RUN R CMD javareconf \
    && R -e "install.packages(c('repr', 'IRdisplay', 'evaluate', 'crayon', 'pbdZMQ', 'devtools', 'uuid', 'digest','Rcpp' ,'devtools','BiocManager','sf','tidyverse','xlsx','hdf5r','igraph'))" \
    && R -e "BiocManager::install(c('multtest','rhdf5'))"

# Rstudio
RUN curl -LO https://download1.rstudio.org/desktop/bionic/amd64/rstudio-1.3.959-amd64.deb \
    && gdebi -n rstudio-1.3.959-amd64.deb \
    && rm rstudio-1.3.959-amd64.deb

# Anaconda3
RUN wget --quiet https://repo.anaconda.com/archive/Anaconda3-2020.11-Linux-x86_64.sh -O ~/anaconda.sh \
     && bash ~/anaconda.sh -b -p /opt/conda \
     && rm ~/anaconda.sh \
     && ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh

# Python
RUN conda update -y conda \
    && pip install -U pip \
    && conda config --add channels conda-forge
RUN conda install numpy numpy_groupies scipy matplotlib pandas seaborn scikit-learn notebook dask plotly black bokeh h5py click jupyter jupyterlab numba pytables \
    && pip install -U jupyterthemes jupyter_contrib_nbextensions python-igraph umap-learn numba

ADD conf conf

RUN useradd -s /bin/bash -m rstudio \
    && echo "rstudio:rstudio" | chpasswd

RUN jupyter notebook --generate-config \
    && cat ./conf >> /root/.jupyter/jupyter_notebook_config.py \
    && rm ./conf
RUN R -e "devtools::install_github('IRkernel/IRkernel')" \
    && R -e "IRkernel::installspec(user = FALSE)"

COPY jupyternotebook.sh jupyternotebook.sh
COPY rserver.sh rserver.sh
